const ROLE_VALUES = ['ADMIN', 'MEMBER'];
const PROJECT_STATUS_VALUES = ['PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED'];
const TASK_STATUS_VALUES = ['TODO', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE'];
const TASK_PRIORITY_VALUES = ['LOW', 'MEDIUM', 'HIGH'];
const NOTIFICATION_TYPE_VALUES = [
  'TASK_ASSIGNED',
  'TASK_UPDATED',
  'COMMENT_ADDED',
  'PROJECT_INVITE',
  'SYSTEM'
];
const ACTIVITY_ENTITY_VALUES = ['PROJECT', 'TASK', 'COMMENT', 'USER', 'AUTH'];

module.exports = {
  ACTIVITY_ENTITY_VALUES,
  NOTIFICATION_TYPE_VALUES,
  PROJECT_STATUS_VALUES,
  ROLE_VALUES,
  TASK_PRIORITY_VALUES,
  TASK_STATUS_VALUES
};
